### PR TITLE
Fix upload schedule

### LINKED ISSUE #130: please figure out schedule builder
I have spent ages trying to get the schedule builder (https://symposion.readthedocs.io/en/latest/schedule.html) to work but I keep getting an error. I'm not sure if I've missed setting something up in admin, or if something's missing or wrong in the csv file or if it's a bug or misconfiguration in the system.

I can get the form up at /schedule/sagta-general-track/edit/ (there is a form url for every schedule you create) but keep getting en error on submission of the csv. 

Please get it working (in staging) with https://github.com/kartoza/qgis.org.za/blob/develop/django_project/conference_schedules/FOSS4GAfrica_schedule.csv asap.

### PR DESCRIPTION
**Pull request by euclidian**
This fixes #130 

There are severals different quote on csv and time format need to be adjusted.
Accepted time format is "HH:MM"

### CODE REVIEW

**Comment by gubuntu** [comment]
OK, so have you managed to get a schedule csv file to be accepted and successfully create the schedule structure? 

Does it fail if there is an existing schedule structure (i.e. you have to delete the existing one first) or does it overwrite it?

**Comment by gubuntu** [comment]
Also, do the schedules automatically appear in the Dashboard once created?

**Comment by euclidian** [comment]
Sorry, forgot to add screenshot.
If there is existing schedule, uploading a new csv will append the schedule.

Schedule's layout is a disaster. I'll create a new issue for that.

image

> Also, do the schedules automatically appear in the Dashboard once created?

No, it will be available on `/schedule`.

**Comment by gubuntu** [comment]
Great, if this is working, please merge and and release

**Pull request merged**
